FROM resin/armhf-alpine:3.6

# add files
ADD ./ /var/www

RUN [ "cross-build-start" ]

# build
RUN set -x \
    && apk add --update nginx hugo \
    && cd /var/www \
    && hugo \
    && apk del hugo \
    && cp /var/www/nginx.conf /etc/nginx/conf.d/default.conf \
    && mkdir -p /run/nginx

RUN [ "cross-build-end" ]

EXPOSE 80

ENTRYPOINT nginx -g 'daemon off;'
